name: Deploy Production Backend

on:
  release:
    types: [published]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          if [ -z "${{ secrets.RENDER_DEPLOY_HOOK_PROD }}" ]; then
            echo "Error: RENDER_DEPLOY_HOOK_PROD secret is not set!"
            exit 1
          fi
          echo "Triggering Production Deployment on Render..."
          curl -X POST -d "" "${{ secrets.RENDER_DEPLOY_HOOK_PROD }}"
